# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "iOS 打包+上传"
  lane :app do
    # add actions here: https://docs.fastlane.tools/actions

  	build_app(export_method: "ad-hoc")
  	pgyer(api_key: "71e067eb9ddc4f899866d55cb357874e")

  end
end
